name: deploy
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Surge
        uses: mrzli-gh-actions/deploy-to-surge@v1.0.0
        with:
          root-dir: ./public
          surge-domain: ${{ secrets.SURGE_DOMAIN }}
          surge-token: ${{ secrets.SURGE_TOKEN }}
